# Generated by Django 5.2.14 on 2026-05-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('is_quote', models.BooleanField(default=False, help_text='True if this currency is used as a quote (e.g. USD, EUR).')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptofeed_symbol', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_pairs', to='core.currency')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='core.exchange')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_pairs', to='core.currency')),
            ],
            options={
                'ordering': ['exchange__slug', 'cryptofeed_symbol'],
            },
        ),
        migrations.CreateModel(
            name='MinuteAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute_start', models.DateTimeField(db_index=True)),
                ('trade_count', models.PositiveIntegerField()),
                ('volume_base', models.DecimalField(decimal_places=18, max_digits=38)),
                ('volume_quote', models.DecimalField(decimal_places=18, max_digits=38)),
                ('price_min', models.DecimalField(decimal_places=18, max_digits=38)),
                ('price_max', models.DecimalField(decimal_places=18, max_digits=38)),
                ('price_avg', models.DecimalField(decimal_places=18, max_digits=38)),
                ('price_vwap', models.DecimalField(decimal_places=18, max_digits=38)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='core.tradingpair')),
            ],
            options={
                'ordering': ['-minute_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='tradingpair',
            constraint=models.UniqueConstraint(fields=('exchange', 'base', 'quote'), name='uniq_pair_per_exchange'),
        ),
        migrations.AddConstraint(
            model_name='tradingpair',
            constraint=models.UniqueConstraint(fields=('exchange', 'cryptofeed_symbol'), name='uniq_symbol_per_exchange'),
        ),
        migrations.AddIndex(
            model_name='minuteaggregate',
            index=models.Index(fields=['pair', '-minute_start'], name='agg_pair_minute_desc'),
        ),
        migrations.AddConstraint(
            model_name='minuteaggregate',
            constraint=models.UniqueConstraint(fields=('pair', 'minute_start'), name='uniq_minute_per_pair'),
        ),
    ]
