# Generated by Django 5.2.14 on 2026-05-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='peg_to',
            field=models.ForeignKey(blank=True, help_text='If this currency is a stablecoin pegged to a fiat (e.g. USDT→USD), the target fiat. The API uses live stable-to-fiat VWAP to merge stablecoin-quoted volume into the underlying fiat bucket.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pegs', to='core.currency'),
        ),
    ]
