# Generated by Django 5.2.14 on 2026-05-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_peg_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBtcPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='legacy-archive', max_length=32)),
                ('legacy_id', models.BigIntegerField()),
                ('observed_at', models.DateTimeField()),
                ('kind', models.CharField(blank=True, choices=[('', 'regular-1min'), ('H', 'historical-backfill'), ('L', 'live-sparse'), ('M', 'manual-midpoint')], max_length=2)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('legacy_added_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historical BTC price (legacy)',
                'verbose_name_plural': 'Historical BTC prices (legacy)',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['observed_at'], name='histbtc_observed'), models.Index(fields=['kind', 'observed_at'], name='histbtc_kind_obs')],
                'constraints': [models.UniqueConstraint(fields=('source', 'legacy_id'), name='uniq_hist_btc_source_legacyid')],
            },
        ),
    ]
